# Welcome to Jekyll!
title: fastlane-plugin-saucectl
email: ian.ross.hamilton@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Test your iOS and and Android apps at scale using Sauce Labs toolkit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ianrhamilton.github.io/fastlane-plugin-saucectl" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: just-the-docs/just-the-docs
permalink: pretty

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
#logo: "/assets/images/sauce.png"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
